# Generated by Django 4.1.3 on 2022-12-05 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0003_alter_candidate_user_alter_recruiter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.BooleanField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('description', models.TextField()),
                ('expiration', models.DateField()),
                ('status', models.BooleanField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tindev.recruiter')),
            ],
        ),
    ]
