# Generated by Django 4.1.3 on 2022-12-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0005_alter_post_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interested_posts',
            field=models.ManyToManyField(related_name='interested', to='tindev.post'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='not_interested_posts',
            field=models.ManyToManyField(related_name='not_interested', to='tindev.post'),
        ),
    ]
