# Generated by Django 4.1.3 on 2022-12-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0006_candidate_interested_posts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to='tindev.candidate')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to='tindev.post')),
            ],
        ),
    ]
