# Generated by Django 4.1.3 on 2022-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0007_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
