# Generated by Django 4.1.3 on 2022-12-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindev', '0004_alter_candidate_bio_alter_candidate_education_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tindev.recruiter'),
        ),
    ]
